title: KAPRA Project
description: Implementation of (k,P)-Anonymity for Time Series Data
remote_theme: pages-themes/hacker@v0.2.0
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge